apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app:1.0.0-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app:1.0.0-16
  template:
    metadata:
      labels:
        app: register-app:1.0.0-16
    spec:
      containers:
        - name: register-app:1.0.0-16
          image: ashfaque9x/register-app:1.0.0-16
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
